-- camiscada.sql

/*
PLAN 1-M BLD 1-M DEPT 1-M DPMC M-1 MACC 1-M COMP

una macchina può essere spostata da un reparto all'altro

*/


PROMPT "Creating structure tables ..."


BEGIN
  FOR RECDIR IN (
      SELECT TABLE_NAME WTNAME FROM USER_TABLES WHERE REGEXP_LIKE (TABLE_NAME,'M19')
    ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || RECDIR.WTNAME;
  END LOOP;
END;
/

CREATE TABLE M19PLAN (
-- ID_M19PLAN NUMBER,
MSHORT VARCHAR2(4),
MDESCRI VARCHAR2(30)
);

@C:\tools\sql\apx41_tblattr M19PLAN APKTS RUN

CREATE TABLE M19BUILDING (
-- ID_M19BUILDING NUMBER,
MSHORT VARCHAR2(4),
MDESCRI VARCHAR2(30),
FK_M19PLAN NUMBER
);

@C:\tools\sql\apx41_tblattr M19BUILDING APKTS RUN

CREATE TABLE M19DEPT (
-- ID_M19DEPT NUMBER,
MSHORT VARCHAR2(4),
MDESCRI VARCHAR2(30),
FK_M19BUILDING NUMBER
--,
--FK_M19DPTMAC NUMBER
);

@C:\tools\sql\apx41_tblattr M19DEPT APKTS RUN

-- ASSOCIATIVA
CREATE TABLE M19DPTMAC (
-- ID_M19DPTMAC NUMBER,
MDTABEG TIMESTAMP,
MDTAEND TIMESTAMP,
FK_M19DEPT NUMBER,
FK_M19MACHINE NUMBER
);

@C:\tools\sql\apx41_tblattr M19DPTMAC APKTS RUN
 
CREATE TABLE M19MACHINE (
-- ID_M19MACHINE NUMBER,
MSHORT VARCHAR2(4),
MDESCRI VARCHAR2(30),
MCLASS VARCHAR2(10),
MDATEINST TIMESTAMP,
MDATESTOP TIMESTAMP,
MIDINVENT VARCHAR2(30)	-- INVENTORY ID , USED WHEN THE MACHINE IS MOVED ON 
-- FK_M19DPTMAC NUMBER
);

@C:\tools\sql\apx41_tblattr M19MACHINE APKTS RUN

CREATE TABLE M19COMPONENT (
-- ID_M19COMPONENT NUMBER,
MSHORT VARCHAR2(4),
MDESCRI VARCHAR2(30),
MDATEINST TIMESTAMP,
MDATESTOP TIMESTAMP,
MVENDOR VARCHAR2(30),
MTYPMTBF NUMBER,        -- MTBF HOURS 
MSERIAL VARCHAR2(30),	
FK_M19MACHINE NUMBER);

@C:\tools\sql\apx41_tblattr M19COMPONENT APKTS RUN

-- SERVE ANCORA?
CREATE TABLE M19LAYOUT (
-- ID_M19LAYOUT NUMBER,
FK_M19COMPONENT NUMBER,
FK_M19COMPFROM NUMBER,
FK_M19COMPTO NUMBER,
MCODEDVC VARCHAR2(20),
MPOSITION VARCHAR2(20),
MLABEL VARCHAR2(20),
MVERSION VARCHAR2(10),
MAUTHOR VARCHAR2(20)
);

@C:\tools\sql\apx41_tblattr M19LAYOUT APKTS RUN

-- USED FOR INI
-- TANK;p1b1d1m1c1;90;50;HLT
-- MCODE DERIVA DAI CAMPI SHORT
CREATE TABLE M19OBJECT (
-- ID_M19OBJECT NUMBER,
MOBJTYPE VARCHAR2(10),
MCODEFROM VARCHAR2(30),
MCODETO VARCHAR2(30),
MACHFROM VARCHAR2(5),
MACHTO VARCHAR2(5),
MPOSIX NUMBER,
MPOSIY NUMBER,
MVERSION VARCHAR2(10),
MVERSION VARCHAR2(10)
);

@C:\tools\sql\apx41_tblattr M19OBJECT APKTS RUN

PROMPT "Structure tables, created"

PROMPT "Creating staging table..."

-- STAGING TABLE
CREATE TABLE M19STGLOG (
-- MWHEN TIMESTAMP,
MDVCID VARCHAR2(30),
MCOMPVAL VARCHAR2(20)
);


@C:\tools\sql\apx41_tblattr KSTLOG APKTS RUN

PROMPT "Staging table, created"

PROMPT "Load rk for structure tables..."

INSERT INTO M19PLAN (
-- ID_M19PLAN ,
MSHORT,MDESCRI) VALUES (
-- 1,
'HQ','HEADQUARTER'); 
INSERT INTO M19PLAN (
-- ID_M19PLAN ,
MSHORT,MDESCRI) VALUES (
-- 2,
'MA','MAGADAN'); 

INSERT INTO M19BUILDING (
-- ID_M19PLAN,
MSHORT,MDESCRI,FK_M19PLAN) 
VALUES (
-- 1,
'B1','BLD1',(SELECT ID_M19PLAN FROM M19PLAN WHERE MSHORT='MA'));

INSERT INTO M19BUILDING (
-- ID_M19PLAN,
MSHORT,MDESCRI,FK_M19PLAN) 
VALUES (
-- 2,
'B2','BLD2',(SELECT ID_M19PLAN FROM M19PLAN WHERE MSHORT='MA'));

INSERT INTO M19DEPT (
-- ID_M19DEPT,
MSHORT,MDESCRI,FK_M19BUILDING)
VALUES (
-- 1,
'MO2','MOLDING',(SELECT ID_M19BUILDING FROM M19BUILDING WHERE MSHORT='B2'));

INSERT INTO M19DEPT (
-- ID_M19DEPT,
MSHORT,MDESCRI,FK_M19BUILDING)
VALUES (
-- 2,
'EX','EXTRUD',(SELECT ID_M19BUILDING FROM M19BUILDING WHERE MSHORT='B2'));

INSERT INTO M19MACHINE (
-- ID_M19MACHINE,
MSHORT,MDESCRI,
-- FK_M19DPTMAC,
MCLASS)
VALUES (
-- 1,
'SRD','RUWTECH20',1,'SHREDDER');
INSERT INTO M19MACHINE (
-- ID_M19MACHINE,
MSHORT,MDESCRI,
-- FK_M19DPTMAC,
MCLASS)
VALUES (
-- 2,
'EXT2','LORENZIN',1,'EXTRUDER');

INSERT INTO M19DPTMAC (MDTABEG,FK_M19DEPT,FK_M19MACHINE) 
VALUES (SYSDATE,(SELECT ID_M19MACHINE FROM M19MACHINE WHERE MSHORT='EXT2'),
(SELECT ID_M19DEPT FROM M19DEPT WHERE MSHORT='EX'));


INSERT INTO M19COMPONENT (
-- ID_M19COMPONENT NUMBER,
MSHORT,MDESCRI,MDATEINST ,MVENDOR ,MTYPMTBF ,FK_M19MACHINE)
VALUES (
-- 1,
'STE','TERM.SENS. EXTRUDER',TO_DATE('01.07.2016','DD.MM.YYYY'),
'TOPSUPPLIER SA',9000,
(SELECT ID_M19MACHINE FROM M19MACHINE WHERE MSHORT='EXT2'));

PROMPT "Rk for structure tables, loaded"

PROMPT "Generating ini..."


-- TANK;p1b1d1m1c1;90;50;HLT

-- CAMPO MCODEDVC VIENE CALCOLATO DALLE TBL MASTER:
INSERT INTO M19LAYOUT (FK_M19COMPONENT,FK_M19COMPFROM, FK_M19COMPTO, MCODEDVC, MPOSITION, MLABEL, MVERSION, MAUTHOR)
VALUES (10260,NULL,NULL,'p1b1d1m2c6','50;100','TRAMOGGIA','1.0','MR');
COMMIT;

-- 10.12.2019 - PER CREARE camiscada.ini prendere da M19LAYOUT e mettere in join con M19MACHINE
-- DA PROVARE...
SELECT T1.MCLASS||';'||T2.MCODEDVC||';'||T2.MPOSITION||';'||T2.MLABEL WRIGA
FROM M19MACHINE T1,M19LAYOUT T2, m19COMPONENT T3
WHERE 1=1
AND T1.ID_M19MACHINE=T3.FK_M19MACHINE
AND T3.ID_M19COMPONENT=T2.FK_M19COMPONENT
UNION ALL
SELECT T1.MCLASS||';'||T2.MCODEDVC||';'||T2.FK_M19COMPFROM||';'||T2.FK_M19COMPTO||';'||T2.MPOSITION||';'||T2.MLABEL WRIGA 
FROM M19MACHINE T1,M19LAYOUT T2, m19COMPONENT T3
WHERE 1=1
AND T1.ID_M19MACHINE=T3.FK_M19MACHINE
AND T3.ID_M19COMPONENT=T2.FK_M19COMPONENT
AND T1.MCLASS='PIPE';

-- LE COLONNE COMP* DI LAYOUT SONO ALIMENTATE DALLE TBL MASTER


-- 09.12.2019 WIP DAL COMPLETARE PER GENERARE IL "camiscada.ini
SELECT 
-- T4.MCLASS||';'||
T1.MSHORT||T2.MSHORT||T3.MSHORT||T5.MSHORT||T6.MSHORT
FROM M19PLAN T1,M19BUILDING T2,M19DEPT T3,M19DPTMAC T4,M19MACHINE T5,M19COMPONENT T6
WHERE 1=1
AND T1.MSHORT='MA'
AND T2.FK_M19PLAN=T1.ID_M19PLAN
AND T3.FK_M19BUILDING=T2.ID_M19BUILDING
AND T4.FK_M19DEPT=T3.ID_M19DEPT
AND T4.FK_M19MACHINE=T5.ID_M19MACHINE
AND T6.FK_M19MACHINE=T5.ID_M19MACHINE
AND T4.MDTABEG IS NOT NULL


